### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dolfinus** [sqlalchemyorg/changelog#6]
Hello.

What to you think about new release which will include changes from list below?
* https://github.com/sqlalchemyorg/changelog/commit/76fd17873bd811046d91ea518b7ee61716c62c2b
* https://github.com/sqlalchemyorg/changelog/commit/ea92fdd64ab5a142ddc0ef7f753dcd5ade452c23

**Comment by zzzeek** [comment]
as you've closed the other PRs that were pending, sure thing.

https://pypi.org/project/changelog/0.5.5/

**Comment by dolfinus** [comment]
Thanks!
