### ISSUE TITLE
Missing version git tags

### ISSUE THREAD

**Issue by kloczek** [sqlalchemyorg/changelog#7]
https://pypi.org/project/changelog/ says that latest version is 0.5.5 but looks like there is no any version tags here

**Comment by zzzeek** [comment]
I release changelog manually using twine and there's not yet any automation to tag these.   Im sure this is common with a lot of projects on pypi.

**Comment by kloczek** [comment]
That is OK. Just pleae start adding tags on next release :)

**Comment by kloczek** [comment]
Just explanation why I've asked abouyt tagging: simple my automation performs additional checks using git tags.

**Comment by zzzeek** [comment]
fixed by #9

**Comment by kloczek** [comment]
Thank you :)
